// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../entities/meal_plan.dart';
import '../entities/recipe.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6719496625513008878),
      name: 'MealPlan',
      lastPropertyId: const obx_int.IdUid(2, 222508286148098768),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8891874079131425183),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 222508286148098768),
            name: 'dayId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'recipes', srcEntity: 'Recipe', srcField: 'mealPlan')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2323773367971043792),
      name: 'Recipe',
      lastPropertyId: const obx_int.IdUid(7, 3333572910343793667),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7855596835509486918),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3745621742714782266),
            name: 'mealId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8416538083613502),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1077257197707958511),
            name: 'instructions',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3375101505032187899),
            name: 'calories',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1538050498258633714),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3333572910343793667),
            name: 'mealPlanId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 7406323545699297081),
            relationTarget: 'MealPlan')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 2323773367971043792),
      lastIndexId: const obx_int.IdUid(1, 7406323545699297081),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    MealPlan: obx_int.EntityDefinition<MealPlan>(
        model: _entities[0],
        toOneRelations: (MealPlan object) => [],
        toManyRelations: (MealPlan object) => {
              obx_int.RelInfo<Recipe>.toOneBacklink(
                      7, object.id, (Recipe srcObject) => srcObject.mealPlan):
                  object.recipes
            },
        getId: (MealPlan object) => object.id,
        setId: (MealPlan object, int id) {
          object.id = id;
        },
        objectToFB: (MealPlan object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.dayId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dayIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final object = MealPlan(dayId: dayIdParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<MealPlan>(
              object.recipes,
              store,
              obx_int.RelInfo<Recipe>.toOneBacklink(
                  7, object.id, (Recipe srcObject) => srcObject.mealPlan));
          return object;
        }),
    Recipe: obx_int.EntityDefinition<Recipe>(
        model: _entities[1],
        toOneRelations: (Recipe object) => [object.mealPlan],
        toManyRelations: (Recipe object) => {},
        getId: (Recipe object) => object.id,
        setId: (Recipe object, int id) {
          object.id = id;
        },
        objectToFB: (Recipe object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final instructionsOffset = object.instructions == null
              ? null
              : fbb.writeString(object.instructions!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.recipeId);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, instructionsOffset);
          fbb.addInt64(4, object.calories);
          fbb.addFloat64(5, object.price);
          fbb.addInt64(6, object.mealPlan.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final mealIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final instructionsParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final caloriesParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final priceParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 14);
          final object = Recipe(
              recipeId: mealIdParam,
              name: nameParam,
              instructions: instructionsParam,
              calories: caloriesParam,
              price: priceParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.mealPlan.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.mealPlan.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MealPlan] entity fields to define ObjectBox queries.
class MealPlan_ {
  /// See [MealPlan.id].
  static final id =
      obx.QueryIntegerProperty<MealPlan>(_entities[0].properties[0]);

  /// See [MealPlan.dayId].
  static final dayId =
      obx.QueryIntegerProperty<MealPlan>(_entities[0].properties[1]);

  /// see [MealPlan.recipes]
  static final recipes =
      obx.QueryBacklinkToMany<Recipe, MealPlan>(Recipe_.mealPlan);
}

/// [Recipe] entity fields to define ObjectBox queries.
class Recipe_ {
  /// See [Recipe.id].
  static final id =
      obx.QueryIntegerProperty<Recipe>(_entities[1].properties[0]);

  /// See [Recipe.recipeId].
  static final recipeId =
      obx.QueryIntegerProperty<Recipe>(_entities[1].properties[1]);

  /// See [Recipe.name].
  static final name =
      obx.QueryStringProperty<Recipe>(_entities[1].properties[2]);

  /// See [Recipe.instructions].
  static final instructions =
      obx.QueryStringProperty<Recipe>(_entities[1].properties[3]);

  /// See [Recipe.calories].
  static final calories =
      obx.QueryIntegerProperty<Recipe>(_entities[1].properties[4]);

  /// See [Recipe.price].
  static final price =
      obx.QueryDoubleProperty<Recipe>(_entities[1].properties[5]);

  /// See [Recipe.mealPlan].
  static final mealPlan =
      obx.QueryRelationToOne<Recipe, MealPlan>(_entities[1].properties[6]);
}
